# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e1f60b8b726ef23470444ea3189f16b91302269a35ba169171d1756a1f98530e68020807461cd08c1b1de1971b5f4450ad576b089bd187082f20129445cef45

test:
  secret_key_base: 30f3439b94a71edf91bbaec200a06ab1e2bdece440177cbc16ff170d78aeed494926232fba4ae6e89ab946a38c172b0bcc65e864669c584f402f4b90c5ec9bed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
